### ISSUE TITLE
As a player, I want to be able to get an overview of what other roles are in the game and what they can do. This allows me to adjust my strategy according to this information.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#11]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#48
- [x] sopra-fs23-group-23/werewolf-client#47
- [x] sopra-fs23-group-23/werewolf-client#46

Task list backend:
- [x] #132

Acceptance Criteria:

- A player can access the information of what roles are present in the current game.
- A player should be able to access the information on how many players had a certain
role at game start.
- A player can see additional information such as the role description of the different
characters.
