### ISSUE TITLE
As a player I want to elect a mayor in the beginning of the game.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#12]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#44
- [x] sopra-fs23-group-23/werewolf-client#43
- [x] sopra-fs23-group-23/werewolf-client#42

Task list backend:
- [x] #133

Acceptance Criteria:

- Before the first night all players can vote for a mayor.
- The person with the most votes gets the role of the mayor.
- If there is no clear winner during this election the game engine chooses a mayor.
