### ISSUE TITLE
As a registered User I want to sign in by providing my chosen username and password.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#2]
Task List frontend:
 - [x] sopra-fs23-group-23/werewolf-client#66
 - [x] sopra-fs23-group-23/werewolf-client#65
 - [x] sopra-fs23-group-23/werewolf-client#64
 
Task List backend:
- [x] #117
- [x] #118

Acceptance Criteria:
- The user can enter a username and a password and click login.
- By clicking the login button, the Server validates if username and password are correct.
- Upon successful validation the user is redirected to the lobby view, otherwise an error is
displayed to the user.
