### ISSUE TITLE
As a werewolf I want to communicate with the other werewolves to determine which player we would like to kill.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#22]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#30
- [x] sopra-fs23-group-23/werewolf-client#29
- [x] sopra-fs23-group-23/werewolf-client#28

Acceptance Criteria:
- The communication takes place in the form of a separate voice or video chat.
- The players who do not occupy the role of werewolves are not able to witness this.
