### ISSUE TITLE
As a werewolf I want to be able to vote for one of the other players to kill them.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#23]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#27
- [x] sopra-fs23-group-23/werewolf-client#26
- [x] sopra-fs23-group-23/werewolf-client#25
- [x] sopra-fs23-group-23/werewolf-client#24

Task list backend:
- [x] #151
- [x] #152
- [x] #153
- [x] #154

Acceptance Criteria:
- A werewolf can vote for a person.
- During the voting the other werewolves can see who voted for whom.
- The player with the most votes dies.
- The werewolves must decide who they want to kill in a certain time frame.
- If two players have the same number of votes after the time runs out, nobody is killed. Thus, someone is only killed if he/she got most of the votes.
- The wolves can change their opinions on the vote they casted.
- Werewolves can also vote for each other to not violate the game logic with the amor.
