### ISSUE TITLE
As a player, I want to be able to vote and discuss my opinion with other players in order to get closer to my game goal.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#30]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#13
- [x] sopra-fs23-group-23/werewolf-client#12
- [x] sopra-fs23-group-23/werewolf-client#11
- [x] sopra-fs23-group-23/werewolf-client#76
- [x] sopra-fs23-group-23/werewolf-client#77

Task list backend:
- [x] #174
- [x] #175
- [x] #189 
- [x] #190 
- [x] #191 
- [x] #192 

Acceptance Criteria:
- The players can communicate by a voice or video chat.
- The players can select a person who they want to vote for.
- Only players who are still alive can take part in the discussion and voting.
- Players can see who voted for whom.
- After a certain time, the voting period ends and the person with the most votes dies. If
two players have the same number of votes, the mayor’s vote decides
