### ISSUE TITLE
As a player, I want to be able to rematch to start a new game in the same lobby.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#37]
Task list frontend:
- [ ] sopra-fs23-group-23/werewolf-client#3
- [ ] sopra-fs23-group-23/werewolf-client#4
- [ ] sopra-fs23-group-23/werewolf-client#5

Task list backend:
- [ ] sopra-fs23-group-23/werewolf-server#43

Acceptance Criteria:
- By pressing the rematch button, the user gets redirected to the lobby screen and stays in the same lobby.
- Players in the lobby are kicked out if the lobby leader doesn’t choose to rematch but leaves the game.
