### ISSUE TITLE
As a logged-in User I want to be able to join a created lobby to join a new game.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#38]
Task list frontend:
- [x] sopra-fs23-group-23/werewolf-client#1
- [x] sopra-fs23-group-23/werewolf-client#2

Task list backend:
- [x] sopra-fs23-group-23/werewolf-server#42
- [x] sopra-fs23-group-23/werewolf-server#186

Acceptance Criteria:
- The user can enter a join code and click a join lobby button to join a game
- After entering a valid code, you are invited into the lobby waiting room, where you can
see the other players
