### ISSUE TITLE
As an admin I want to configure which roles are in my game and how many of each, to customize my game.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#7]
Task list frontend:
- [ ] sopra-fs23-group-23/werewolf-client#55
- [ ] sopra-fs23-group-23/werewolf-client#54
- [ ] sopra-fs23-group-23/werewolf-client#53

Task list backend:
- [ ] #126

Acceptance Criteria:
- Admin customizes how many werewolves there are in the game.
- After this, the admin can select roles, which are assigned to the non-werewolf players.
- The number of roles is limited by the number of non-werewolf players.

**Comment by mirovv** [comment]
this issue was closed by mistake in commit: 5bbf9f3
